-- ==========================================
-- 1. CRÉATION DE LA TABLE 'tracks'
-- ==========================================
CREATE TABLE public.tracks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  franchise TEXT NOT NULL, 
  game TEXT NOT NULL,      
  arranger TEXT,
  youtube_link TEXT,
  arrangement_status TEXT DEFAULT 'À faire', 
  play_status TEXT DEFAULT 'Déchiffrage',    
  duration TEXT,           
  "imageUrl" TEXT,         
  description TEXT, -- NOUVEAU CHAMP DEMANDÉ
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 2. CRÉATION DE LA TABLE 'concert_tracks'
-- ==========================================
CREATE TABLE public.concert_tracks (
  concert_id BIGINT REFERENCES public.concerts(id) ON DELETE CASCADE,
  track_id BIGINT REFERENCES public.tracks(id) ON DELETE CASCADE,
  play_order INTEGER NOT NULL DEFAULT 0, 
  is_secret BOOLEAN DEFAULT false,       
  PRIMARY KEY (concert_id, track_id)     
);

-- ==========================================
-- 3. GESTION DE LA SÉCURITÉ (RLS)
-- ==========================================
ALTER TABLE public.tracks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.concert_tracks ENABLE ROW LEVEL SECURITY;

-- Les visiteurs peuvent lire
CREATE POLICY "Accès public en lecture des morceaux" 
ON public.tracks FOR SELECT USING (true);

CREATE POLICY "Accès public en lecture des setlists" 
ON public.concert_tracks FOR SELECT USING (true);

-- Seuls les admins peuvent modifier
CREATE POLICY "Accès total morceaux pour les admins" 
ON public.tracks FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Accès total setlists pour les admins" 
ON public.concert_tracks FOR ALL USING (auth.role() = 'authenticated');


-- ==========================================
-- 4. FIX COLONNE INUTILE
-- ==========================================

ALTER TABLE public.concerts DROP COLUMN time;