-- 1. Création de la table des membres
CREATE TABLE public.members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL, -- Identifiant pour l'URL (ex: 'pierre')
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  "photoUrl" TEXT NOT NULL,
  instruments JSONB NOT NULL DEFAULT '[]'::jsonb, -- Stockage flexible (JSON)
  "customFields" JSONB NOT NULL DEFAULT '[]'::jsonb, -- Stockage flexible (JSON)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Sécurité RLS
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Accès public en lecture des membres" 
ON public.members FOR SELECT USING (true);

CREATE POLICY "Accès total membres pour les admins" 
ON public.members FOR ALL USING (auth.role() = 'authenticated');

-- 3. Injection de vos données actuelles !
INSERT INTO public.members (slug, name, description, "photoUrl", instruments, "customFields")
VALUES
(
  'pierre', 
  'Pierre', 
  'Il se débrouille bien pour arranger les morceaux, mais pas plus d''un par semaine.', 
  'https://placehold.co/400x400/1a1a1a/00ffcc?text=Pierre', 
  '[{"name": "Saxophone Alto"}, {"name": "Mélodica à ses heures perdues"}]', 
  '[{"label": "Citation préférée", "icon": "💬", "values": ["« Pas plus d''un par semaine ! »", "« J''ai dit pas plus d''un par semaine, hein Jean ! »", "« On reprend à B pour Jean »", "« Moins vite William, moins vite ! »"]}, {"label": "Musique préférée", "icon": "🎵", "values": ["Dire Dire Docks (Mario 64)"]}, {"label": "Jeu préféré", "icon": "🎮", "values": ["Wordle"]}, {"label": "Saveur de yaourt préférée", "icon": "🥛", "values": ["Noix de coco"]}]'
),
(
  'william', 
  'William', 
  'Il peut jouer de presque 10 instruments différents mais n''est toujours pas capable de jouer au bon tempo.', 
  'https://placehold.co/400x400/1a1a1a/00ffcc?text=William', 
  '[{"name": "Saxophone Soprano"}]', 
  '[{"label": "Citation préférée", "icon": "💬", "values": ["« Paul je comprends pas ce que tu dis »", "« Venez on le refait mais 10x plus vite »"]}, {"label": "Musique préférée", "icon": "🎵", "values": ["Rayman origins : food boss"]}, {"label": "Jeu préféré", "icon": "🎮", "values": ["Portal", "Rayman origins"]}, {"label": "Passion envahissante", "icon": "👀", "values": ["Doctor Who", "Doctor Who ?", "Parfois, Doctor Who ...", "Un peu (trop) Doctor Who", "Doctor Qui ?"]}]'
),
(
  'jean', 
  'Jean', 
  'Plus c''est grave mieux c''est, et si en plus c''est dans le cadre d''une folie il en sera assurément !', 
  'https://placehold.co/400x400/1a1a1a/00ffcc?text=Jean', 
  '[{"name": "Saxophone Baryton"}, {"name": "Mélodica"}, {"name": "j-sax"}, {"name": "bamboo sax"}, {"name": "piano"}, {"name": "guitar"}]', 
  '[{"label": "Citation préférée", "icon": "💬", "values": ["« Je connais un très bon club de kung fu »", "un pour tous, tous bourrin"]}, {"label": "Musique préférée", "icon": "🎵", "values": ["Claire obscure : Monoco theme"]}, {"label": "Jeu préféré", "icon": "🎮", "values": ["Sifu", "Claire obscure (oui c''est d''un banal...)", "OuterWild"]}]'
),
(
  'paul', 
  'Paul', 
  'Le boss de la batterie. Même pas besoin de partoche, l''adaptation c''est sa clé !', 
  'https://placehold.co/400x400/1a1a1a/00ffcc?text=Paul', 
  '[{"name": "Batterie"}, {"name": "Piano"}]', 
  '[{"label": "Citation préférée", "icon": "💬", "values": ["« Je vois pas vos pieds ! »"]}, {"label": "Musique préférée", "icon": "🎵", "values": ["Whiplash"]}, {"label": "Jeu préféré", "icon": "🎮", "values": ["Doom Eternal", "Crypt of the NecroDancer"]}]'
);

--Créer un bucket "batsax-media"

-- 1. Autoriser tout le monde à VOIR les images (Lecture publique)
CREATE POLICY "Images visibles par tous" 
ON storage.objects FOR SELECT 
USING ( bucket_id = 'batsax-media' );

-- 2. Autoriser les administrateurs (connectés) à AJOUTER des images (Upload)
CREATE POLICY "Upload pour les admins" 
ON storage.objects FOR INSERT 
WITH CHECK ( bucket_id = 'batsax-media' AND auth.role() = 'authenticated' );

-- 3. Autoriser les administrateurs à MODIFIER des images
CREATE POLICY "Modification pour les admins" 
ON storage.objects FOR UPDATE 
USING ( bucket_id = 'batsax-media' AND auth.role() = 'authenticated' );

-- 4. Autoriser les administrateurs à SUPPRIMER des images
CREATE POLICY "Suppression pour les admins" 
ON storage.objects FOR DELETE 
USING ( bucket_id = 'batsax-media' AND auth.role() = 'authenticated' );