-- ==========================================
-- 1. CRÉATION DES TABLES
-- ==========================================

CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  username TEXT,
  avatar_url TEXT,
  role TEXT DEFAULT 'user',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.community_tracks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  game TEXT NOT NULL,
  youtube_link TEXT,
  musescore_link TEXT,
  spotify_link TEXT,
  status TEXT DEFAULT 'en_vote', 
  admin_comment TEXT,
  accepted_track_id BIGINT REFERENCES public.tracks(id) ON DELETE SET NULL,
  game_image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.community_votes (
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  track_id BIGINT REFERENCES public.community_tracks ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, track_id)
);


-- ==========================================
-- 2. FONCTIONS ET TRIGGERS
-- ==========================================

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'
  );
$$ LANGUAGE sql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, username, avatar_url)
  VALUES (
    new.id, 
    -- CORRECTION ICI : -> pour le premier, ->> pour le second
    COALESCE(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->'custom_claims'->>'global_name', 'Fan de batSax'), 
    COALESCE(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture', '')
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- ==========================================
-- 3. RAPPATRIEMENT DES ANCIENS UTILISATEURS
-- ==========================================

INSERT INTO public.profiles (id, username, avatar_url, role)
SELECT 
  id, 
  -- CORRECTION ICI AUSSI
  COALESCE(raw_user_meta_data->>'full_name', raw_user_meta_data->'custom_claims'->>'global_name', 'Utilisateur existant'),
  COALESCE(raw_user_meta_data->>'avatar_url', raw_user_meta_data->>'picture', ''),
  'user'
FROM auth.users
ON CONFLICT (id) DO NOTHING;


-- ==========================================
-- 4. SÉCURITÉ (RLS)
-- ==========================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_tracks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_votes ENABLE ROW LEVEL SECURITY;

-- PROFILS
CREATE POLICY "Lecture publique des profils" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Modification propre profil" ON public.profiles FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id AND role = 'user'); 
CREATE POLICY "Admins full access profiles" ON public.profiles FOR ALL USING (public.is_admin());

-- COMMUNITY TRACKS
CREATE POLICY "Lecture publique suggestions" ON public.community_tracks FOR SELECT USING (true);
CREATE POLICY "Modif par auteur" ON public.community_tracks FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Suppr par auteur" ON public.community_tracks FOR DELETE USING (auth.uid() = user_id);
CREATE POLICY "Admin full access tracks" ON public.community_tracks FOR ALL USING (public.is_admin());
CREATE POLICY "Limite de 5 suggestions" ON public.community_tracks FOR INSERT 
WITH CHECK (auth.uid() = user_id AND (SELECT count(*) FROM public.community_tracks WHERE user_id = auth.uid()) < 5);

-- COMMUNITY VOTES
CREATE POLICY "Lecture publique votes" ON public.community_votes FOR SELECT USING (true);
CREATE POLICY "Vote reserve membres" ON public.community_votes FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Suppr propre vote" ON public.community_votes FOR DELETE USING (auth.uid() = user_id);

-- SÉCURISATION DU CATALOGUE BATSAX
DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.concerts;
CREATE POLICY "Admin full access concerts" ON public.concerts FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.tracks;
CREATE POLICY "Admin full access bat tracks" ON public.tracks FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.concert_tracks;
CREATE POLICY "Admin full access setlists" ON public.concert_tracks FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.members;
CREATE POLICY "Admin full access members" ON public.members FOR ALL USING (public.is_admin());

-- 5. RECHARGEMENT DU CACHE DE L'API SUPABASE
NOTIFY pgrst, 'reload schema';