-- ==========================================
-- 1. CRÉATION DES TABLES
-- ==========================================

CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  username TEXT,
  avatar_url TEXT,
  role TEXT DEFAULT 'user',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.community_tracks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  game TEXT NOT NULL,
  game_image_url TEXT, -- Stockage de la jaquette RAWG
  youtube_link TEXT,
  musescore_link TEXT,
  spotify_link TEXT,
  status TEXT DEFAULT 'en_vote', 
  admin_comment TEXT,
  accepted_track_id BIGINT REFERENCES public.tracks(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.community_votes (
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  track_id BIGINT REFERENCES public.community_tracks ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, track_id)
);


-- ==========================================
-- 2. FONCTIONS ET TRIGGERS
-- ==========================================

-- Fonction pour vérifier si l'utilisateur est admin
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'
  );
$$ LANGUAGE sql SECURITY DEFINER;

-- Trigger pour créer le profil à l'inscription
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, username, avatar_url)
  VALUES (
    new.id, 
    COALESCE(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->'custom_claims'->>'global_name', 'Fan de batSax'), 
    COALESCE(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture', '')
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- ==========================================
-- 3. RAPPATRIEMENT DES UTILISATEURS
-- ==========================================

INSERT INTO public.profiles (id, username, avatar_url, role)
SELECT 
  id, 
  COALESCE(raw_user_meta_data->>'full_name', raw_user_meta_data->'custom_claims'->>'global_name', 'Utilisateur existant'),
  COALESCE(raw_user_meta_data->>'avatar_url', raw_user_meta_data->>'picture', ''),
  'user'
FROM auth.users
ON CONFLICT (id) DO NOTHING;


-- ==========================================
-- 4. SÉCURITÉ (RLS)
-- ==========================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_tracks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_votes ENABLE ROW LEVEL SECURITY;

-- --- POLITIQUES PROFILES ---
DROP POLICY IF EXISTS "Lecture publique des profils" ON public.profiles;
CREATE POLICY "Lecture publique des profils" ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Modification propre profil" ON public.profiles;
CREATE POLICY "Modification propre profil" ON public.profiles 
FOR UPDATE 
USING (auth.uid() = id) 
WITH CHECK (auth.uid() = id AND (role = 'user' OR public.is_admin())); 

DROP POLICY IF EXISTS "Admins full access profiles" ON public.profiles;
CREATE POLICY "Admins full access profiles" ON public.profiles FOR ALL USING (public.is_admin());

-- --- POLITIQUES COMMUNITY TRACKS ---
DROP POLICY IF EXISTS "Lecture publique suggestions" ON public.community_tracks;
CREATE POLICY "Lecture publique suggestions" ON public.community_tracks FOR SELECT USING (true);

DROP POLICY IF EXISTS "Auteur peut modifier titre et liens" ON public.community_tracks;
CREATE POLICY "Auteur peut modifier titre et liens" ON public.community_tracks 
FOR UPDATE 
USING (auth.uid() = user_id AND status = 'en_vote') 
WITH CHECK (auth.uid() = user_id AND status = 'en_vote');

DROP POLICY IF EXISTS "Suppr par auteur" ON public.community_tracks;
CREATE POLICY "Suppr par auteur" ON public.community_tracks 
FOR DELETE 
USING (auth.uid() = user_id AND status = 'en_vote');

DROP POLICY IF EXISTS "Admin full access tracks" ON public.community_tracks;
CREATE POLICY "Admin full access tracks" ON public.community_tracks FOR ALL USING (public.is_admin());

DROP POLICY IF EXISTS "Limite de 5 suggestions" ON public.community_tracks;
CREATE POLICY "Limite de 5 suggestions" ON public.community_tracks 
FOR INSERT 
WITH CHECK (
  auth.uid() = user_id 
  AND (SELECT count(*) FROM public.community_tracks WHERE user_id = auth.uid()) < 5
);

-- --- POLITIQUES COMMUNITY VOTES ---
DROP POLICY IF EXISTS "Lecture publique votes" ON public.community_votes;
CREATE POLICY "Lecture publique votes" ON public.community_votes FOR SELECT USING (true);

DROP POLICY IF EXISTS "Vote reserve membres" ON public.community_votes;
CREATE POLICY "Vote reserve membres" ON public.community_votes FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Suppr propre vote" ON public.community_votes;
CREATE POLICY "Suppr propre vote" ON public.community_votes FOR DELETE USING (auth.uid() = user_id);

-- --- SÉCURISATION DU CATALOGUE BATSAX (ADMIN ONLY) ---
-- On s'assure qu'aucune politique "authenticated" ne traîne
DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.concerts;
DROP POLICY IF EXISTS "Enable update for authenticated users only" ON public.concerts;
DROP POLICY IF EXISTS "Admin full access concerts" ON public.concerts;
CREATE POLICY "Admin full access concerts" ON public.concerts FOR ALL USING (public.is_admin());
CREATE POLICY "Public read concerts" ON public.concerts FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.tracks;
DROP POLICY IF EXISTS "Admin full access bat tracks" ON public.tracks;
CREATE POLICY "Admin full access bat tracks" ON public.tracks FOR ALL USING (public.is_admin());
CREATE POLICY "Public read tracks" ON public.tracks FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.concert_tracks;
DROP POLICY IF EXISTS "Admin full access setlists" ON public.concert_tracks;
CREATE POLICY "Admin full access setlists" ON public.concert_tracks FOR ALL USING (public.is_admin());
CREATE POLICY "Public read setlists" ON public.concert_tracks FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable all for authenticated users" ON public.members;
DROP POLICY IF EXISTS "Admin full access members" ON public.members;
CREATE POLICY "Admin full access members" ON public.members FOR ALL USING (public.is_admin());
CREATE POLICY "Public read members" ON public.members FOR SELECT USING (true);


-- ==========================================
-- 5. FINITION
-- ==========================================
NOTIFY pgrst, 'reload schema';