create table public.concerts (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  date timestamp with time zone not null,
  name text not null,
  location text not null,
  description text null,
  "imageUrl" text null,
  "videoUrl" text null,
  "locationLink" text null,
  time text null,
  constraint concert_pkey primary key (id)
) TABLESPACE pg_default;

